controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.24
  min_vel_x: 0.1 
  max_vel_theta: 0.8 
  min_vel_theta: -0.8 

  min_in_place_vel_theta: 0.8

  acc_lim_x: 2.0
  acc_lim_y: 0.0
  acc_lim_theta: 0.8

  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.05

  sim_time: 0.8

  vx_samples: 18.0
  vtheta_samples: 20.0

  pdist_scale: 0.6 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.02

  holonomic_robot: false
